### ISSUE TITLE
Problems OmniKassa Payment Provider

### ISSUE THREAD

**Issue by snieling** [uWebshop/PaymentProviders#7]
Does somebody has problems with the OmniKassa Payment Provider because i get the follow error:

887 [6] ERROR uWebshop.Umbraco6.UmbracoLoggingService - [Thread 32] HandlePaymentRequest With Online Payment FAILED

Have no idea what i have to do!

**Comment by snieling** [comment]
Problem solved!

Besides, maybe it's a good idea to post the GrandtotalInCents to iDeal instead of the ChargedOrderAmountInCents (who's is gonna pay the taxes?).

**Comment by mnwsmit** [comment]
Thank you Sander!
Thanks also for the suggestion. However, ChargedOrderAmountInCents is specifically designed to be sent to the payment provider. This is because in some cases the VAT is not charged, especially so when the order is sent to a different fiscal area than the shop (e.g. send outside EU from an in-EU shop).
